fix: disable gunicorn control socket to fix startup under non-root user
gunicorn 25+ enables a control socket by default, created under
\$HOME/.gunicorn/gunicorn.ctl. The non-root appuser added earlier has
HOME=/home/appuser, which doesn't exist and can't be created (no write
access to /home), so gunicorn failed to start with "Control server
error: [Errno 13] Permission denied". We don't use the gunicornc
control interface, so disable it with --no-control-socket.